import = ["~/.config/alacritty/themes/tokyonight_dark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "SemiBold"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Light Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Light"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1

[window.padding]
x = 2
y = 2
